# Node.js

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - '*'
    exclude:
      - 'source/_draft'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    sudo npm install hexo-cli -g
  displayName: 'Installing Hexo CLI...'

- script: |
    hexo generate
  displayName: 'Generating blog...'
- task: CopyFiles@2
  inputs:
    Contents: '**'
    SourceFolder: 'public'
    TargetFolder: '$(Pipeline.Workspace)'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'deployment'