# Node.js

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build'

- script: |
    npm install hexo-cli -g & hexo generate
  displayName: 'Installing Hexo CLI...'

- script: |
    hexo generate
  displayName: 'Generating blog...'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)\\public'
    artifact: 'deployment'