# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.15.1
          
      - name: npm install, install hexo-cli
        run: |
          npm install -g hexo-cli
          npm install
      
      - name: Generate static site
        run: |
          hexo generate
          
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.TEST_AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./public/
